### ISSUE TITLE
Add me on discord

### ISSUE THREAD

**Issue by Hoodgail** [zhiyan114/Firey-Bot#18]
Old account got banned.
Oranges#7774

**Comment by zhiyan114** [comment]
lmao what you do. Also ur FR is disabled, send me @ Domain Controller#3160

**Comment by Hoodgail** [comment]
![Screenshot_20230304_235131_Discord.jpg](https://user-images.githubusercontent.com/45743294/222942326-f2c64149-3d02-4933-82b2-e8d1776e6bd0.jpg)

**Comment by Hoodgail** [comment]
I'm stupid Hold up

**Comment by Hoodgail** [comment]
Try now, I enabled it
